[build]
  command = "pip install -r requirements-serverless.txt"
  functions = "netlify/functions"
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200

[build.environment]
  PYTHON_VERSION = "3.8"
