-- Função para verificar e criar a tabela medicamentos
CREATE OR REPLACE FUNCTION public.verificar_tabela_medicamentos()
RETURNS text AS $$
DECLARE
  tabela_existe BOOLEAN;
  resultado TEXT;
BEGIN
  -- Verificar se a tabela existe
  SELECT EXISTS (
    SELECT FROM information_schema.tables 
    WHERE table_schema = 'public' 
    AND table_name = 'medicamentos'
  ) INTO tabela_existe;
  
  -- Se a tabela não existir, criar
  IF NOT tabela_existe THEN
    CREATE TABLE public.medicamentos (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      substancia TEXT NOT NULL,
      cnpj TEXT,
      laboratorio TEXT,
      codigo_ggrem TEXT,
      registro TEXT,
      ean_1 TEXT,
      ean_2 TEXT,
      ean_3 TEXT,
      produto TEXT,
      apresentacao TEXT,
      classe_terapeutica TEXT,
      tipo_de_produto TEXT,
      regime_de_preco TEXT,
      restricao_hospitalar BOOLEAN,
      cap BOOLEAN,
      confaz_87 BOOLEAN,
      icms_0 BOOLEAN,
      analise_recursal BOOLEAN,
      lista_concessao_credito BOOLEAN,
      comercializacao_2022 BOOLEAN,
      tarja TEXT,
      pf_sem_impostos DECIMAL(10,2),
      pf_0 DECIMAL(10,2),
      pf_12 DECIMAL(10,2),
      pf_12_alc DECIMAL(10,2),
      pf_17 DECIMAL(10,2),
      pf_17_alc DECIMAL(10,2),
      pf_17_5 DECIMAL(10,2),
      pf_17_5_alc DECIMAL(10,2),
      pf_18 DECIMAL(10,2),
      pf_18_alc DECIMAL(10,2),
      pf_19 DECIMAL(10,2),
      pf_19_alc DECIMAL(10,2),
      pf_19_5 DECIMAL(10,2),
      pf_19_5_alc DECIMAL(10,2),
      pf_20 DECIMAL(10,2),
      pf_20_alc DECIMAL(10,2),
      pf_20_5 DECIMAL(10,2),
      pf_21 DECIMAL(10,2),
      pf_21_alc DECIMAL(10,2),
      pf_22 DECIMAL(10,2),
      pf_22_alc DECIMAL(10,2),
      pmc_sem_imposto DECIMAL(10,2),
      pmc_0 DECIMAL(10,2),
      pmc_12 DECIMAL(10,2),
      pmc_12_alc DECIMAL(10,2),
      pmc_17 DECIMAL(10,2),
      pmc_17_alc DECIMAL(10,2),
      pmc_17_5 DECIMAL(10,2),
      pmc_17_5_alc DECIMAL(10,2),
      pmc_18 DECIMAL(10,2),
      pmc_18_alc DECIMAL(10,2),
      pmc_19 DECIMAL(10,2),
      pmc_19_alc DECIMAL(10,2),
      pmc_19_5 DECIMAL(10,2),
      pmc_19_5_alc DECIMAL(10,2),
      pmc_20 DECIMAL(10,2),
      pmc_20_alc DECIMAL(10,2),
      pmc_20_5 DECIMAL(10,2),
      pmc_21 DECIMAL(10,2),
      pmc_21_alc DECIMAL(10,2),
      pmc_22 DECIMAL(10,2),
      pmc_22_alc DECIMAL(10,2),
      data_publicacao DATE,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );
    
    -- Criar índices para melhorar a performance
    CREATE INDEX idx_medicamentos_substancia ON public.medicamentos (substancia);
    CREATE INDEX idx_medicamentos_data_publicacao ON public.medicamentos (data_publicacao);
    
    -- Configurar permissões RLS
    ALTER TABLE public.medicamentos ENABLE ROW LEVEL SECURITY;
    
    -- Criar políticas de acesso
    CREATE POLICY "Permitir acesso para todos os usuários autenticados" 
    ON public.medicamentos 
    FOR ALL 
    TO authenticated 
    USING (true);
    
    resultado := 'Tabela medicamentos criada com sucesso';
  ELSE
    -- Verificar se há colunas faltando e adicionar se necessário
    IF NOT EXISTS (
      SELECT FROM information_schema.columns 
      WHERE table_schema = 'public' 
      AND table_name = 'medicamentos' 
      AND column_name = 'tipo_de_produto'
    ) THEN
      ALTER TABLE public.medicamentos ADD COLUMN tipo_de_produto TEXT;
    END IF;
    
    IF NOT EXISTS (
      SELECT FROM information_schema.columns 
      WHERE table_schema = 'public' 
      AND table_name = 'medicamentos' 
      AND column_name = 'regime_de_preco'
    ) THEN
      ALTER TABLE public.medicamentos ADD COLUMN regime_de_preco TEXT;
    END IF;
    
    -- Adicione aqui outras verificações de colunas se necessário
    
    resultado := 'Tabela medicamentos já existe e foi verificada';
  END IF;
  
  RETURN resultado;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
